### ISSUE TITLE
Switch to using libmypaint as a shared lib

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#535]
MyPaint should build so that it links an installed libmypaint.so at runtime. This will require us to drop the submodule, and a good time to do that is _really early on_ in a new alpha/active dev cycle :sweat_smile: 
### Todo
- [x] Update the docs to say "build libmypaint separately first, and install it" as a first step, essentially
  - MyPaint's C++ parts should use regular shared-lib libmypaint initially
  - I'm not sure about introspection in libmypaint right now. That feels a little incomplete (or maybe I just haven't twiddled the right build vars to get it working properly).
- [x] Do whatever's necessary in the build system to invoke pkg-config to build against and link libmypaint
- [x] Make sure the test runner (`run_brushlib_tests()`) can still be built and run somehow, with the right configuration of libmypaint installed.
- [x] Fix the docs to remove all traces of "brushlib" and the submodule in our build instructions

**Comment by achadwick** [comment]
So libmypaint went sharedlib by default today, which has meant a few changes to mypaint to support it. I note from #539 that we'll need to ensure that the test runner function can be called from MyPaint's CI and testing suite. There's only one function we need, but it's buried in libmypaint-tests.a, which is built but not installed by libmypaint, and which also forms part of its own test suite.

(#542 is a temporary stopgap really. Time to disentangle things properly.)

**Comment by achadwick** [comment]
@Jehan is doing fantastic work making an autotools build in mypaint/libmypaint#32. Disentangled code soon for MyPaint too ☺

**Comment by Jehan** [comment]
@achadwick Please see the PR #538. It has now a new commit which does the "disentangling" into MyPaint! MyPaint does not use any submodule there anymore and build (then run) perfectly. :-)

**Comment by hartwork** [comment]
Hi there!

It would be awesome to have a new release of mypaint that uses external libmypaint. Right now, people can only use _either_ Gimp 2.9.4 (which depends on libmypaint 1.3.x which blocks mypaint <1.2.2) or mypaint (see https://bugs.gentoo.org/show_bug.cgi?id=602066). Please help me unblocking mypaint. Thanks!

Best, Sebastian

**Comment by odysseywestra** [comment]
I think this is technically done @achadwick .
